# Generated by Django 2.2.24 on 2021-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0002_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='comentario',
            field=models.TextField(default='Aun no hay comentarios sobre esta noticia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuario',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='', max_length=60),
        ),
    ]
