# Generated by Django 2.2.24 on 2021-07-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0003_auto_20210707_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='formu',
            fields=[
                ('nombre_formu', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
