# Generated by Django 2.2.24 on 2021-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0005_auto_20210707_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
