# Generated by Django 2.2.24 on 2021-07-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0006_noticia_publicar'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('portada', models.ImageField(upload_to='galeria')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caos_news.noticia')),
            ],
        ),
    ]
