# Generated by Django 2.2.24 on 2021-07-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caos_news', '0007_galeria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='periodistas',
            new_name='periodista',
        ),
    ]
